#!/usr/bin/env bash

source ~/.dotfiles/styles/palette.sh

options=(
	style=round
	width=2.0
	hidpi=on
	active_color="${marykate_color15}"
	inactive_color="${marykate_color8}"
)

borders "${options[@]}"
