#!/usr/bin/env bash

source ~/.dotfiles/styles/palette.sh

_hex() { printf '0xff%s\n' "${1:1}"; }

borders_opts=(
	style=round
	width=2.0
	hidpi=on
	active_color="$(_hex "$marykate_arch")"
	inactive_color="$(_hex "$marykate_color8")"
)

borders "${borders_opts[@]}"
