return {
  {
    "milanglacier/minuet-ai.nvim",
    opts = {
      provider = "openai_fim_compatible",
      n_completions = 1,
      context_window = 512,
      virtualtext = {
        auto_trigger_ft = {
          -- "python",
          -- "lua",
          -- "javascript",
          -- "javascriptreact",
          -- "typescript",
          -- "typescriptreact",
          -- "bash",
          -- "sh",
          -- "zsh",
          -- "json",
          -- "jsonc",
          -- "yaml",
          -- "toml",
          -- "html",
          -- "css",
          -- "scss",
          -- "go",
          -- "rust",
          -- "c",
          -- "cpp",
          -- "java",
          -- "kotlin",
          -- "ruby",
          -- "php",
          -- "sql",
        },
        keymap = {
          accept = "<A-A>",
          accept_line = "<A-a>",
          accept_n_lines = "<A-z>",
          prev = "<A-[>",
          next = "<A-]>",
          dismiss = "<A-e>",
        },
      },
      provider_options = {
        openai_fim_compatible = {
          api_key = "TERM",
          name = "Ollama",
          end_point = "http://localhost:11434/v1/completions",
          model = "qwen2.5-coder:7b",
          optional = {
            max_tokens = 56,
            top_p = 0.9,
          },
        },
      },
    },
  },
}
