set -g @color_inactive "#707b90"
set -g @color_active "#ffffff"
set -g @color_special ""
set -g @color_special_1 ""
set -g @color_special_3 ""
set -g @color_special_4 ""
set -g @color_special_5 ""
set -g @color_special_6 ""
set -g @color_special_7 ""
set -g @color_special_8 ""
set -g @color_special_9 ""
